"""Added product type restriction for token

Revision ID: 19a3e9a8c40f
Revises: 2b55f905bbc8
Create Date: 2026-02-20 19:03:58.085532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a3e9a8c40f'
down_revision: Union[str, None] = '2b55f905bbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_tokens', sa.Column('product_type', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_purchase_tokens_product_type_product_types'), 'purchase_tokens', 'product_types', ['product_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_purchase_tokens_product_type_product_types'), 'purchase_tokens', type_='foreignkey')
    op.drop_column('purchase_tokens', 'product_type')
    # ### end Alembic commands ###
