"""Added product schema version

Revision ID: 2b55f905bbc8
Revises: 0242ab49f2ae
Create Date: 2026-02-20 14:59:47.895025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b55f905bbc8'
down_revision: Union[str, None] = '0242ab49f2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_schema_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_product_schema_versions_version_gt_than_zero')),
    sa.ForeignKeyConstraint(['product_type'], ['product_types.id'], name=op.f('fk_product_schema_versions_product_type_product_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_schema_versions')),
    sa.UniqueConstraint('product_type', 'version', name=op.f('uq_product_schema_versions_product_type_version'))
    )
    op.add_column('products', sa.Column('schema', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_products_schema_product_schema_versions'), 'products', 'product_schema_versions', ['schema'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_schema_product_schema_versions'), 'products', type_='foreignkey')
    op.drop_column('products', 'schema')
    op.drop_table('product_schema_versions')
    # ### end Alembic commands ###
