"""Added features

Revision ID: 73173a0c651e
Revises: 7f35e1126b0e
Create Date: 2026-03-07 13:37:23.854418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73173a0c651e'
down_revision: Union[str, None] = '7f35e1126b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_features_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_features_catalog')),
    sa.UniqueConstraint('code', name=op.f('uq_product_features_catalog_code'))
    )
    op.create_table('product_type_features',
    sa.Column('product_type', sa.Integer(), nullable=False),
    sa.Column('feature', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature'], ['product_features_catalog.id'], name=op.f('fk_product_type_features_feature_product_features_catalog')),
    sa.ForeignKeyConstraint(['product_type'], ['product_types.id'], name=op.f('fk_product_type_features_product_type_product_types')),
    sa.PrimaryKeyConstraint('product_type', 'feature', name=op.f('pk_product_type_features'))
    )
    op.create_table('product_features',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['product_features_catalog.id'], name=op.f('fk_product_features_feature_id_product_features_catalog')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_features_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'feature_id', name=op.f('pk_product_features'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_features')
    op.drop_table('product_type_features')
    op.drop_table('product_features_catalog')
    # ### end Alembic commands ###
