"""Replaced purchase token with token_hash

Revision ID: 7f35e1126b0e
Revises: 19a3e9a8c40f
Create Date: 2026-02-20 21:45:17.086681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f35e1126b0e'
down_revision: Union[str, None] = '19a3e9a8c40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_tokens', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_purchase_tokens_token'), table_name='purchase_tokens')
    op.create_index(op.f('ix_purchase_tokens_token_hash'), 'purchase_tokens', ['token_hash'], unique=True)
    op.drop_column('purchase_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_purchase_tokens_token_hash'), table_name='purchase_tokens')
    op.create_index(op.f('ix_purchase_tokens_token'), 'purchase_tokens', ['token'], unique=True)
    op.drop_column('purchase_tokens', 'token_hash')
    # ### end Alembic commands ###
